version: '3.7'
services:
  want:
    build: django_want
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_want:/usr/src/django_want/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=want
      - POSTGRES_PASSWORD=want
      - POSTGRES_DB=want
      - PGDATA=/var/lib/postgresql/data
volumes:
  postgres_data:

