version: '3.7'
services:
  want:
    build:
      context: django_want
      dockerfile: Dockerfile.prod
    command: gunicorn django_want.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - static:/home/app/web/static
    - media:/home/app/web/media
    expose:
    - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    volumes:
    - static:/home/app/web/static
    - media:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - want
volumes:
  postgres_data:
  static:
  media: