# Generated by Django 3.1 on 2021-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_init_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_bird',
            field=models.DateField(null=True),
        ),
    ]
