# Generated by Django 3.1 on 2021-05-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0002_author_year_of_bird_null_true'),
        ('books', '0001_init_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='chapters',
            options={'verbose_name': 'chapter', 'verbose_name_plural': 'chapters'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_book_name',
        ),
        migrations.AddField(
            model_name='books',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
    ]
